export const data = [
           {id:Math.random(),title:"Breakfast 1",description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.",price:"31 $",category:"Breakfast",img:"1.jpg"},
           {id:Math.random(),title:"Lunch 1",description:"Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",price:"60 $",category:"Lunch",img:"2.jpg"},
           {id:Math.random(),title:"Dinner 1",description:"There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",price:"60 $",category:"Dinner",img:"3.jpg"},
           {id:Math.random(),title:"Breakfast 2",description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.",price:"31 $",category:"Breakfast",img:"4.jpg"},
           {id:Math.random(),title:"Lunch 2",description:"Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",price:"60 $",category:"Lunch",img:"5.jpg"},
           {id:Math.random(),title:"Dinner 2",description:"There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",price:"60 $",category:"Dinner",img:"6.jpg"},
           {id:Math.random(),title:"Breakfast 3",description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.",price:"31 $",category:"Breakfast",img:"7.jpg"},
           {id:Math.random(),title:"Lunch 3",description:"Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",price:"60 $",category:"Lunch",img:"8.jpg"},
           {id:Math.random(),title:"Dinner 3",description:"There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",price:"60 $",category:"Dinner",img:"9.jpg"},
           {id:Math.random(),title:"Breakfast 4",description:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.",price:"31 $",category:"Breakfast",img:"10.jpg"},
        ]